### ISSUE TITLE
rpmalloc.lib(rpmalloc.c.obj) : error LNK2001

### ISSUE THREAD

**Issue by RuohanLixyf** [iisys-hof/map-matching-2#4]
is there anyone has the same issue below? When i use the 'cmake --build .'

```
[5/5] Linking CXX executable src\map_matching_2.exe
FAILED: src/map_matching_2.exe
C:\Windows\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=src\CMakeFiles\map_matching_2.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x86\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx86\x86\link.exe /nologo src\CMakeFiles\map_matching_2.dir\main.cpp.obj  /out:src\map_matching_2.exe /implib:src\map_matching_2.lib /pdb:src\map_matching_2.pdb /version:0.0 /machine:X86 /INCREMENTAL:NO /subsystem:console  /INCREMENTAL:NO /LTCG  _deps\rpmalloc-build\rpmalloc.lib  src\app\app.lib  src\library\library.lib  _deps\boost-build\lib\libboost_thread-vc143-mt-s-x32-1_86.lib  _deps\boost-build\lib\libboost_chrono-vc143-mt-s-x32-1_86.lib  _deps\boost-build\lib\libboost_serialization-vc143-mt-s-x32-1_86.lib  _deps\gpx-build\gpx\gpx.lib  _deps\zlib-build\zlibstatic.lib  _deps\expat-build\libexpatMT.lib  _deps\bz2-build\bz2_static.lib  _deps\boost-build\lib\libboost_program_options-vc143-mt-s-x32-1_86.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx86\x86\link.exe /nologo src\CMakeFiles\map_matching_2.dir\main.cpp.obj /out:src\map_matching_2.exe /implib:src\map_matching_2.lib /pdb:src\map_matching_2.pdb /version:0.0 /machine:X86 /INCREMENTAL:NO /subsystem:console /INCREMENTAL:NO /LTCG _deps\rpmalloc-build\rpmalloc.lib src\app\app.lib src\library\library.lib _deps\boost-build\lib\libboost_thread-vc143-mt-s-x32-1_86.lib _deps\boost-build\lib\libboost_chrono-vc143-mt-s-x32-1_86.lib _deps\boost-build\lib\libboost_serialization-vc143-mt-s-x32-1_86.lib _deps\gpx-build\gpx\gpx.lib _deps\zlib-build\zlibstatic.lib _deps\expat-build\libexpatMT.lib _deps\bz2-build\bz2_static.lib _deps\boost-build\lib\libboost_program_options-vc143-mt-s-x32-1_86.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST:EMBED,ID=1" failed (exit code 1120) with the following output:
   Creating library src\map_matching_2.lib and object src\map_matching_2.exp
rpmalloc.lib(rpmalloc.c.obj) : error LNK2001: unresolved external symbol _rpmalloc_module_init
src\map_matching_2.exe : fatal error LNK1120: 1 unresolved externals
ninja: build stopped: subcommand failed.
```

**Comment by addy90** [comment]
Hi, thank you for trying out my tool!

Can you please start building from scratch and post the full commands and logfiles (as attachment)? In case there is private information like your name, you can of course censor (replace with XXXXX) in your logfile.
Please also post your Windows and compiler information, which version you are using.

From your output I don't know if there were errors during configuration time. The dependencies are built during configuration (the first CMake command) and thus the build of course fails if there were errors at configuration time.

Because the builds are cached to some extent during configuration, please delete the build directory in advance before you do it again.

Moreover: Do you have "Windows Long Paths" enabled as I explained in the README at "Hint for Windows building"?
In case you only receive the error with rpmalloc, you can disable that library in particular with `-DENABLE_RPMALLOC=OFF` CMake command during configuration, but I am not sure if this is the issue or the error happens at an earlier time during your build.

Using the prebuild binaries is not an option for you I suppose?

Thank you!

**Comment by addy90** [comment]
Hey @RuohanLixyf,
I found out which commands work reliable to build the application under Windows without an IDE:
```shell
# Windows cmd.exe (in PowerShell first enter: cmd)
# Initialize compiler environment
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
# Now build the program
"C:\path\to\cmake.exe" -DCMAKE_MAKE_PROGRAM="C:\path\to\ninja.exe" -G Ninja -DCMAKE_BUILD_TYPE=Release -B build
"C:\path\to\cmake.exe" --build build --parallel %NUMBER_OF_PROCESSORS% --target install
```

Of course you need to adjust the paths to CMake and Ninja to your setup.

I will update the README accordingly with the next update. The `-A x64` or `-DCMAKE_GENERATOR_PLATFORM=x64` are unsupported in Ninja and don't work that way, so forget my earlier response concerning this please!

The main trick is that the `vcvars64.bat` file from the compiler suite is called first in a cmd (does not work in a PowerShell directly, type cmd and Enter first in a PowerShell to open the "old" console terminal). Then the correct compiler is set up in temporary environment variables and then the build process correctly executes and the binaries are in the `run` subdirectory structure.

Can you please try it out and give me feedback if it worked?

Thank you!

**Comment by RuohanLixyf** [comment]
> Hey @RuohanLixyf, I found out which commands work reliable to build the application under Windows without an IDE:
> 
> ```shell
> # Windows cmd.exe (in PowerShell first enter: cmd)
> # Initialize compiler environment
> "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
> # Now build the program
> "C:\path\to\cmake.exe" -DCMAKE_MAKE_PROGRAM="C:\path\to\ninja.exe" -G Ninja -DCMAKE_BUILD_TYPE=Release -B build
> "C:\path\to\cmake.exe" --build build --parallel %NUMBER_OF_PROCESSORS% --target install
> ```
> 
> Of course you need to adjust the paths to CMake and Ninja to your setup.
> 
> I will update the README accordingly with the next update. The `-A x64` or `-DCMAKE_GENERATOR_PLATFORM=x64` are unsupported in Ninja and don't work that way, so forget my earlier response concerning this please!
> 
> The main trick is that the `vcvars64.bat` file from the compiler suite is called first in a cmd (does not work in a PowerShell directly, type cmd and press Enter first in a PowerShell to open the "old" console terminal). Then the correct compiler is set up in temporary environment variables and then the build process correctly executes and the binaries are put in the `run` subdirectory structure.
> 
> Can you please try it out and give me feedback if it worked?
> 
> Thank you!

Thank you for the quick response. I'm in the process of rebuilding it using the code you provided. However, I've encountered a few other issues along the way. I managed to resolve some of them, but now, as I'm nearing the final stage, a new error has occurred:

...updated 18275 targets...
-- Adding library: libosmium
-- Found Threads: TRUE
-- Found Protozero: C:/Users/XXX/map-matching-2/build/_deps/protozero-src/include (found suitable version "1.7.1", minimum required is "1.6.3")
-- Found Osmium: C:/Users/XXX/map-matching-2/build/_deps/libosmium-src/include
-- Adding external libraries - SUCCESS
-- Build only library: OFF
-- Install all shared libraries: OFF
-- Found Boost: C:/Users/XXX/map-matching-2/build/_deps/boost-build/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found version "1.86.0") found components: serialization thread chrono
-- Set default install prefix: C:/Users/XXX/map-matching-2/run/msvc/release
-- Found Boost: C:/Users/XXX/map-matching-2/build/_deps/boost-build/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found version "1.86.0") found components: thread program_options
-- Rpath set to: $ORIGIN/../lib
-- Install only necessary libraries
-- Found Boost: C:/Users/XXX/map-matching-2/build/_deps/boost-build/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found version "1.86.0") found components: unit_test_framework
-- Performing Test _deprecated_declarations
-- Performing Test _deprecated_declarations - Failed
-- Configuring incomplete, errors occurred!

**Comment by addy90** [comment]
Hi @RuohanLixyf 

glad you were able to make it further in the process!

In the new logfile that you posted, I cannot see the error messages, unfortunately, only that errors occured, but not where. I think they are statet earlier. Can you please attach the complete logfile (you can search and replace your username with Notepad++ for example in advance) in case you have further errors?

I am just guessing right now, but are the errors during the Boost subbuild?
Did you enable long paths on your Windows system as explained in the "Hints for Windows building" collapsed text in the [README](https://github.com/iisys-hof/map-matching-2?tab=readme-ov-file#building)?
If not, please read that part in the README and try that out first.

Use the registry setting that is explained in the Windows article and please reboot your system.
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem]
"LongPathsEnabled"=dword:00000001
```
Don't forget to reboot your system!

Then delete the build directory completely before you start building from scratch again, just to make sure, because some parts are not rebuild properly during CMake configuration when there were errors.

If it still does not work, please let me know!

Thank you!

**Comment by addy90** [comment]
Hey, I am closing this issue since it became stale. If there are still issues, please feel free to reopen the issue!
