### ISSUE TITLE
Packaging libraries in python

### ISSUE THREAD

**Issue by duongvgm** [iisys-hof/map-matching-2#5]
Hi, great solution
If it can be packaged into a very good python library, do you have any plans for that?

**Comment by addy90** [comment]
Hi, thank you for your feedback!

I tried out a Python implementation before I switched to C++ in this implementation.
The old implementation "prototype" still exists here: https://github.com/iisys-hof/map-matching
However it is far less advanced and extremely slow in comparison.
It also is under the restrictive AGPL 3.0 license like map-matching-2 here, because the concepts and ideas are shared and I want to make sure everyone benefits from further development of this concept.

So for some details:
My main issue with Python was the computational speed. I debugged and profiled the old implementation _a lot_ but was not able to make it acceptable fast. If you read my publication (https://doi.org/10.1111/tgis.13107) you know about the _Candidate Adoption_ feature. I had the idea back then but the Python implementation was already that slow that I could not implement my idea there, the speed was already beyond anything practical. The candidate adoption feature massively increases the amount of candidates and a lot more routes need to be computed and compared subsequently.

The main issues for the speed in Python were the frequent calls to C subroutines in the GeoPandas and subsequent Shapely calls, which needed to copy the data from Python to C and back, which needed time. And moreover, the pure Python-interpreted Dijkstra's Shortest Path algorithm from the NetworkX package which simply could not run fast due to the run-time interpretation. Works very well for single routing requests, but I need to compute hundreds of millions of routes in seconds. The packages are great to use and I still like to use them for quick Python scripts, no offense, these are very fine packages, but for my specific map matching idea, they were not suitable concerning the computational speed needs that I have.

If you are even more interested in the Python speed in comparison to other programming languages, you can read more about it in this article:
```
Rui Pereira, Marco Couto, Francisco Ribeiro, Rui Rua, Jácome Cunha, João Paulo Fernandes, and João Saraiva. 2017.
Energy efficiency across programming languages: how do energy, time, and memory relate?
In Proceedings of the 10th ACM SIGPLAN International Conference on Software Language Engineering (SLE 2017).
Association for Computing Machinery, New York, NY, USA, 256–267.
https://doi.org/10.1145/3136014.3136031
```
You can find the paper and all used code here: https://sites.google.com/view/energy-efficiency-languages

If you watch Table 4, you see that Python code is by a factor of 71.90 slower than the baseline C code, C++ is only by a factor of 1.56 slower than the C code. However, that depends on the use case, for example in Table 3 in the binary-tree case, the C and C++ code are similarly fast. So there might have been some implementation differences between C and C++ and some overlooked optimizations why their C++ code is sometimes slower in their benchmarks. Moreover, C++ compilers have improved a lot since 2017 and often produce faster code today than back then. But I am already going into too much detail.

Back to the topic:
When I implemented my ideas in Python, I was not able to achieve the computational speed that I needed, despite huge profiling and benchmarking efforts. Moreover, some design decisions that I made with the Python code that were quick to write were slower to compute in the end. With the ideas that I still had in mind, i.e., Candidate Adoption, Python was a dead end for me. So the decision was to move entirely to C++ so that I have freedom concerning the data structures and algorithms for maximising computational speed. With these speed gains, I was in turn able to implement the quality improvements that I had in mind, such as candidate adoption, the Markov Decision Process implementation, the improved metrics, and more.

The C++ version here has over 30k lines of C++ code right now and is probably one of the most complex map matching implementations out there today. It contains a lot of C++ specific performance improvements, such as using references and pointers, which are not available or easily achievable in Python. I would have a hard up to impossible time to make my concept to work in pure Python.

So no, no plans for a Python implemtation. I guess the tool would not work at all in Python, like a current next-gen 3D game implemented in C++ would probably not work in pure Python, because of the computational speed (and memory usage) needs.

Now it could of course be possible to make the library "Python-compatible" in writing a Python wrapper so that Python applications can call the C++ subroutines directly. However, the library needs quite a difficult setup to work (with opening the memory-mapped files, starting the worker-thread-pools, and so on), as you can see in the app subfolder that contains the CLI interface for the library part of this software. So the usage might not be as easy as one is used to in Python, especially because of all the parameters this application has.

Moreover, since the application is under AGPL 3.0 a Python-wrapper for the library part would also fall under AGPL 3.0, which means that all applications that use the Python-wrapper would also fall under AGPL 3.0 when they are published. The library is not really meant to be separated from this application, so putting the whole application and library under the AGPL 3.0 is no issue and ensures that further development remains free and open to anyone. However, having a library that is meant to be used in different applications under AGPL 3.0 would be quite restricting. Anyone who wants to build a different interface on the library part is of course welcome to do this, but needs to put the code under AGPL 3.0 when the work is released.

So no, there are also no plans for creating a Python-wrapper.

What _is_ possible in Python already is the following:
I would suggest that you call the map_matching_2 binary as a subprocess. This way, the strong separation is intact and the application that uses map_matching_2 does not fall under AGPL 3.0, because it still counts as a separate work then.

When you use the `--readline --console` arguments combined, you can pass via stdin a WKT track and get the result on the stdout as WKT match, for example like this:

```shell
./map_matching_2-1.0.0-x86_64.AppImage --match --input data/floating-car-data/network/ --read-line --console
```

You could use Shell pipelining (`echo "LINESTRING(...)" | ./map_matching_2 ...`) or you open the subprocess in Python directly as in the command above and use the [communicate](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) method. This way you can directly get results in your Python application and send the tracks one after another. I never tried it our myself yet, but it should work. If not, please create a new issue of course, with a replicable example, please! Alternatively, you can write your data into a CSV file with Python, match these with a regular call, and then continue with another Python script that reads the results. You can put all the calls in a shell script, of course, to automate it.

I made this answer a bit longer and more in-depth so that when future questions around this topic arise, they might already been answered.

I hope you agree with me and you are of course welcome to contribute!

**Comment by duongvgm** [comment]
Hi @addy90
Thanks for your quick and detailed response.
As you said, I have also found a solution to my problem using the map_matching_2 binary package, it is just a little bit more complicated. But that's okay, it's not a big deal; speed is the most important thing in this problem.
Thanks again for your work. Have a nice day and good health.

**Comment by addy90** [comment]
Hi @duongvgm,

Great that you found a solution that is working for you with my application!
If you can and want to tell me a bit more about it, without revealing any research details of course, I might be able to give you some additional tips and tricks if there are any!

In the long run I also want to add an HTTP REST-API, the structure and architecture are already prepared for that, but it will not come this year anymore. When it is done, it will facilitate the usage in Python and other programming languages even more.

I will close this issue because I won't write a Python-API as explained above, but feel free to continue discussion with me around my tool and how to improve using it!

Best regards!
